---
name: Canvas App Lint

permissions:
  id-token: write
  contents: write

on:
  workflow_call:
    inputs:
      root:
        required: false
        default: appsource
        type: string
      lint-path:
        required: false
        default: .github/linters/canvasapps-lint.json
        type: string

jobs:
  connect-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check project repo
        uses: actions/checkout@v4

      - name: Checkout common lint repo
        uses: actions/checkout@v4
        with:
          repository: your-org/common-repo
          ref: main
          path: common
          
      - name: Check Canvas Apps
        shell: pwsh
        run: |
          ./github/linters/canvasapp-lint.ps1 `
            -Root "${{ inputs.root }}" `
            -ConfigPath "./common/${{ inputs.lint-path }}"
    
