---
name: Canvas App Lint

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      root:
        required: false
        default: appsource
        type: string
      lint-path:
        required: false
        default: .github/linters/pp-canvasapps-lint.json
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4

      - name: Checkout common lint repo
        uses: actions/checkout@v4
        with:
          repository: gpjspr/gpj-common
          ref: main
          path: common

      - name: Ensure PowerShell
        run: |
          pwsh --version

      - name: Run Canvas App Lint
        shell: pwsh
        run: |
          $root = "${{ inputs.root }}"
          $config = "./common/${{ inputs.lint-path }}"

          if (!(Test-Path $root)) {
            Write-Error "Root path '$root' does not exist"
            exit 1
          }

          if (!(Test-Path $config)) {
            Write-Error "Config path '$config' does not exist"
            exit 1
          }

          ./common/.github/linters/pp-canvasapps-lint.ps1 `
            -Root $root `
            -ConfigPath $config

      - name: Display Summary
        if: always()
        shell: pwsh
        run: |
          $summaryFile = $env:GITHUB_STEP_SUMMARY
          if (-not [string]::IsNullOrEmpty($summaryFile) -and (Test-Path $summaryFile)) {
              Write-Host "### Canvas App Lint Summary"
              Get-Content $summaryFile | ForEach-Object { Write-Host $_ }
          }
      
      - name: Upload full lint artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: canvas-lint-full
          path: common/canvas-lint-full.md
          
