---
name: Update Configuration File
permissions:
  contents: write
  id-token: write
on:
  workflow_call:
    inputs:
      solutionname:
        description: 'The power platform solution name'
        required: true
        type: string

jobs:
  update-configuration:
    name: Process
    runs-on: ubuntu-latest

       
    steps:
       # Checkout the CALLING repo (not the shared repo)
      - name: Checkout repo
        id: check_repo_extract
        uses: actions/checkout@v4

             
      # Install PAC CLI
      - name: Install PAC CLI
        id: install_pac
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Ensure PAC is available
      - name: Add PAC to PATH
        id: pac_path
        shell: bash
        run: |
          echo "$(dirname "${POWERPLATFORMTOOLS_PACPATH}")" >> "$GITHUB_PATH"

      # Create temporary settings file
      - name: Temporary Settings File
        shell: pwsh
        run: |
          $settingsPath = "configuration/${{ inputs.solutionname }}-settings.json"
          pac solution create-settings --solution-zip "./exports/unmanaged/${{ inputs.solutionname }}.zip" --settings-file $settingsPath
          
          $existingFile = "configuration/DEV/${{ inputs.solutionname }}-settings.json"
          $tempFile = "configuration/${{ inputs.solutionname }}-settings.json"
          
          $existing = Get-Content $existingFile -Raw | ConvertFrom-Json
          $new = Get-Content $tempFile -Raw | ConvertFrom-Json

          $added = @()
          $removed = @()
          $summaryFile = $env:GITHUB_STEP_SUMMARY
          
          foreach ($param in $new.EnvironmentVariables) {
              $match = $existing.EnvironmentVariables | Where-Object { $_.SchemaName -eq $param.SchemaName }
              if (-Not $match) {
                  $added += $param
                  Write-Host "::warning::New setting detected: $($param.SchemaName)"
                  $existing.EnvironmentVariables += $param
              }
          }

          foreach ($param in $existing.EnvironmentVariables) {
              if (-Not ($new.EnvironmentVariables | Where-Object { $_.SchemaName -eq $param.SchemaName })) {
                  Write-Host "::warning::setting removed: $($param.SchemaName)"
                  $removed += $param
              }
          }
      
          if ($added.Count -gt 0) {
            Write-Host "::warning::$($removed.Count) settings added - Manually update the configuration files with values"
            Add-Content $summaryFile "### 🟢 New Settings Detected"
            Add-Content $summaryFile "| SchemaName | DefaultValue |"
            Add-Content $summaryFile "|------------|-------------|"
            foreach ($param in $added) {
                $defaultVal = if ($param.DefaultValue) { $param.DefaultValue } else { "" }
                Add-Content $summaryFile "| $($param.SchemaName) | $defaultVal |"
            }
            Add-Content $summaryFile "`n"
            
            $existing | ConvertTo-Json -Depth 10 | Set-Content $existingFile
          }
          
          if ($removed.Count -gt 0) {
            Write-Host "::error::$($removed.Count) settings removed - Manually update the configuration files"
              Add-Content $summaryFile "### 🔴 Removed Settings Detected"
              Add-Content $summaryFile "| SchemaName | DefaultValue |"
              Add-Content $summaryFile "|------------|-------------|"
              foreach ($param in $removed) {
                  $defaultVal = if ($param.DefaultValue) { $param.DefaultValue } else { "" }
                  Add-Content $summaryFile "| $($param.SchemaName) | $defaultVal |"
              }
              Add-Content $summaryFile "`n"
          }

          if (($added.Count -gt 0) -or ($removed.Count -gt 0)) {
            Add-Content $summaryFile "### 🟠 Manually update the configuration files with values"
            Add-Content $summaryFile "`n"
          }
          
          

      # commit the changes
      - name: Commit changes
        id: commit_changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git status
          git diff --stat
          git commit -m "Automated extract of ${{ inputs.solutionname }}"

      # push to the repo
      - name: Push changes
        id: push_repo
        if: success()
        run: git push origin HEAD
