---
name: Update SharePoint Schema
permissions:
  contents: write
  id-token: write
on:
  workflow_call:
    inputs:
      solutionname:
        required: true
        type: string
      siteurl:
        required: true
        type: string

     
env:
  BUILD_VERSION: 1.0.0.0
  AZ_TENANT_ID: d3e62a06-7979-468d-a1a1-110e7c24c8d1
  AZ_CLIENT_ID: 3df7eaa5-11a5-4e72-9c44-04715669df8b

jobs:
  apply-solution:
    name: Apply Schema
    runs-on: ubuntu-latest

    steps:
      # get branch and config
      - name: Determine Environment from Branch
        id: env
        run: |
          BRANCH="${GITHUB_REF_NAME}"

          if [[ $BRANCH == test/* ]]; then
            ENV_NAME="TEST"
          elif [[ $BRANCH == uat/* ]]; then
            ENV_NAME="UAT"
          elif [[ $BRANCH == releases/* ]]; then
            ENV_NAME="PROD"
          else
            echo "### 🟠 Invalid branch. Must be test/*, uat/* or releases/* " >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          
        # Install PnP
      - name: Install PowerShell and PnP PowerShell
        id: install_pnp
        
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell
          pwsh -Command "Install-Module PnP.PowerShell -Force -Scope CurrentUser"

        # Checkout the CALLING repo (not the shared repo)
      - name: Checkout repo
        id: checkout_repo
        uses: actions/checkout@v4
  
        # Azure login (OIDC)
      - name: Az CLI login
        id: az_login
        uses: azure/login@v2
        with:
            # these need to be EDF items. Do not need to store as variables, are constant. Are not secrets
          client-id: ${{ env.AZ_CLIENT_ID }}
          tenant-id: ${{ env.AZ_TENANT_ID }}
          allow-no-subscriptions: true

        # check sharepointconfig folder
      - name: Check Solution folder
        id: check_folders
        run: |
            mkdir -p sharepointconfig
        
        #connect pnp and apply schema 
      - name: Appy SharePoint PnP site template
        id: export_sitetemplate
        shell: pwsh
        run: |

          $token = az account get-access-token --resource https://bsispdev.sharepoint.com --query accessToken -o tsv
          Connect-PnPOnline -Url ${{ inputs.siteurl }} -AccessToken $token
          Invoke-PnPSiteTemplate -Path "./sharepointconfig/${{ inputs.solutionname }}.xml"

      
